import { StyleSheet } from "react-native";
import type { AppColors } from "./colors";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      backgroundColor: colors.primary,
      paddingHorizontal: 24,
      paddingTop: 56,
      paddingBottom: 24,
      borderBottomLeftRadius: 24,
      borderBottomRightRadius: 24,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 12,
    },
    headerStack: {
      flex: 1,
    },
    headerTitle: {
      color: "#FFFFFF",
      fontSize: 30,
      fontWeight: "700",
    },
    headerSubtitle: {
      color: "rgba(255,255,255,0.85)",
      fontSize: 16,
      marginTop: 4,
    },
    content: {
      flex: 1,
      paddingHorizontal: 24,
      paddingVertical: 20,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      marginBottom: 16,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    balanceLabel: {
      color: colors.textMuted,
      fontSize: 14,
      marginBottom: 4,
    },
    balanceAmount: {
      color: colors.primary,
      fontSize: 40,
      fontWeight: "800",
    },
    actionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 12,
      marginTop: 8,
    },
    actionButton: {
      width: "47%",
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.secondary,
    },
    actionIcon: {
      fontSize: 28,
      marginBottom: 8,
    },
    actionLabel: {
      color: colors.text,
      fontSize: 15,
      fontWeight: "600",
      textAlign: "center",
    },
    primaryButton: {
      backgroundColor: colors.accent,
      borderRadius: 16,
      minHeight: 56,
      paddingVertical: 16,
      alignItems: "center",
      marginTop: 8,
    },
    primaryButtonText: {
      color: "#FFFFFF",
      fontSize: 18,
      fontWeight: "700",
    },
    secondaryButton: {
      backgroundColor: colors.secondary,
      borderRadius: 16,
      minHeight: 56,
      paddingVertical: 16,
      alignItems: "center",
      marginTop: 8,
    },
    secondaryButtonText: {
      color: colors.primary,
      fontSize: 18,
      fontWeight: "700",
    },
    input: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: "#CBD5E1",
      borderRadius: 16,
      paddingHorizontal: 16,
      minHeight: 52,
      fontSize: 16,
      color: colors.text,
      marginBottom: 12,
    },
    label: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 6,
    },
    listItem: {
      backgroundColor: colors.surface,
      borderRadius: 16,
      padding: 16,
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
    },
    listItemTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.text,
    },
    listItemSubtitle: {
      fontSize: 13,
      color: colors.textMuted,
      marginTop: 2,
    },
    languageRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 8,
      marginBottom: 8,
    },
    langChip: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: "rgba(255,255,255,0.16)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.2)",
    },
    langChipActive: {
      backgroundColor: "#FFFFFF",
    },
    langChipText: {
      color: "#FFFFFF",
      fontSize: 12,
      fontWeight: "600",
    },
    langChipTextActive: {
      color: colors.primary,
    },
    errorText: {
      color: colors.danger,
      marginBottom: 8,
    },
    currencyBadge: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.surface,
      borderRadius: 20,
      paddingHorizontal: 12,
      paddingVertical: 6,
      gap: 6,
      alignSelf: "flex-start",
    },
    flagText: {
      fontSize: 20,
    },
    currencyCode: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.primary,
    },
    tabContent: {
      flex: 1,
      paddingHorizontal: 24,
      paddingVertical: 20,
    },
    tabCard: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      padding: 16,
      marginBottom: 16,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    tabPill: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: colors.secondary,
      alignSelf: "flex-start",
    },
    tabPillText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    sectionToggleRow: {
      flexDirection: "row",
      gap: 10,
      marginBottom: 16,
    },
    sectionToggle: {
      flex: 1,
      borderRadius: 16,
      paddingVertical: 12,
      alignItems: "center",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sectionToggleActive: {
      backgroundColor: colors.secondary,
      borderColor: colors.accent,
    },
    sectionToggleText: {
      color: colors.textMuted,
      fontWeight: "700",
    },
    sectionToggleTextActive: {
      color: colors.primary,
    },
  });
}
