import { Platform, StyleSheet } from "react-native";
import type { AppColors } from "./colors";
import { brand } from "./brand";

export const layout = {
  maxContentWidth: 480,
  radiusSm: 10,
  radiusMd: 16,
  radiusLg: 20,
};

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: colors.background,
    },
    contentShell: {
      width: "100%",
      maxWidth: layout.maxContentWidth,
      alignSelf: "center",
      paddingHorizontal: 16,
      paddingBottom: 24,
    },
    header: {
      backgroundColor: colors.background,
      paddingHorizontal: 16,
      paddingTop: Platform.OS === "web" ? 20 : 52,
      paddingBottom: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    headerRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      marginBottom: 8,
    },
    headerStack: {
      flex: 1,
    },
    headerTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: "700",
      letterSpacing: -0.3,
    },
    headerSubtitle: {
      color: colors.textMuted,
      fontSize: 13,
      marginTop: 4,
      fontWeight: "400",
    },
    headerTopRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    homeButton: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: brand.buttonRadius,
      backgroundColor: colors.surfacePurple,
      borderWidth: 1,
      borderColor: colors.border,
    },
    homeButtonText: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: "600",
    },
    homeHeaderCompact: {
      backgroundColor: colors.background,
      paddingTop: Platform.OS === "web" ? 16 : 48,
      paddingBottom: 16,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    homeHeaderTop: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    homeGreeting: {
      color: colors.text,
      fontSize: 22,
      fontWeight: "700",
      letterSpacing: -0.3,
    },
    homeGreetingSub: {
      color: colors.textMuted,
      fontSize: 13,
      marginTop: 4,
      fontWeight: "400",
    },
    homeTagline: {
      color: colors.primary,
      fontSize: 13,
      fontWeight: "600",
      marginTop: 6,
    },
    homeRouteLine: {
      color: colors.text,
      fontSize: 13,
      fontWeight: "500",
      marginTop: 4,
    },
    logoutLink: {
      paddingVertical: 4,
      paddingHorizontal: 2,
    },
    logoutLinkText: {
      color: colors.textMuted,
      fontSize: 12,
      fontWeight: "500",
    },
    balanceCard: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      padding: 20,
      marginTop: 8,
      marginBottom: 16,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.1,
      shadowRadius: 18,
      elevation: 4,
    },
    balanceCardGradientTint: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      height: 4,
      backgroundColor: colors.accent,
      borderTopLeftRadius: layout.radiusLg,
      borderTopRightRadius: layout.radiusLg,
    },
    balanceLabel: {
      color: colors.textMuted,
      fontSize: 13,
      fontWeight: "500",
      marginBottom: 4,
    },
    balanceAmount: {
      color: colors.text,
      fontSize: 36,
      fontWeight: "700",
      letterSpacing: -0.5,
    },
    balanceHint: {
      color: colors.textMuted,
      fontSize: 13,
      marginTop: 6,
    },
    walletStatusRow: {
      flexDirection: "row",
      alignItems: "center",
      marginTop: 12,
      gap: 6,
    },
    walletStatusDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.primary,
    },
    walletStatusText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: "600",
    },
    savingsStat: {
      color: colors.success,
      fontSize: 13,
      fontWeight: "600",
      marginTop: 10,
    },
    primaryActionButton: {
      backgroundColor: colors.accent,
      borderRadius: layout.radiusMd,
      minHeight: 52,
      paddingVertical: 14,
      paddingHorizontal: 20,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 10,
      marginBottom: 16,
      shadowColor: colors.accent,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
      elevation: 3,
    },
    primaryActionButtonPressed: {
      opacity: 0.92,
      transform: [{ scale: 0.99 }],
    },
    primaryActionButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },
    quickActionsGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginBottom: 20,
    },
    quickActionTile: {
      width: "48%",
      minWidth: 96,
      flexGrow: 1,
      backgroundColor: colors.surface,
      borderRadius: 16,
      paddingVertical: 14,
      paddingHorizontal: 10,
      alignItems: "flex-start",
      borderWidth: 1,
      borderColor: colors.border,
    },
    quickActionTileWide: {
      width: "100%",
    },
    quickActionIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 12,
      backgroundColor: colors.surfacePurple,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 8,
    },
    quickActionLabel: {
      color: colors.text,
      fontSize: 12,
      fontWeight: "600",
      textAlign: "center",
      lineHeight: 16,
    },
    sectionHeaderRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginBottom: 10,
    },
    sectionTitle: {
      fontSize: 13,
      fontWeight: "700",
      color: colors.text,
      textTransform: "uppercase",
      letterSpacing: 0.8,
    },
    sectionLink: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.accent,
    },
    activityRow: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    activityIconWrap: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.secondary,
      alignItems: "center",
      justifyContent: "center",
      marginRight: 12,
    },
    activityBody: {
      flex: 1,
    },
    activityTitle: {
      fontSize: 14,
      fontWeight: "600",
      color: colors.text,
    },
    activityMeta: {
      fontSize: 12,
      color: colors.textMuted,
      marginTop: 2,
    },
    activityAmount: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.text,
    },
    activityAmountPositive: {
      color: colors.savings,
    },
    insightCard: {
      backgroundColor: colors.surface,
      borderRadius: layout.radiusMd,
      padding: 16,
      marginTop: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    insightBadge: {
      alignSelf: "flex-start",
      backgroundColor: colors.secondary,
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      marginBottom: 10,
    },
    insightBadgeText: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.3,
      textTransform: "uppercase",
    },
    insightTitle: {
      fontSize: 15,
      fontWeight: "700",
      color: colors.text,
      marginBottom: 4,
    },
    insightLine: {
      fontSize: 13,
      color: colors.textMuted,
      lineHeight: 20,
    },
    insightSavings: {
      fontSize: 14,
      fontWeight: "700",
      color: colors.savings,
      marginTop: 8,
    },
    content: {
      flex: 1,
      paddingHorizontal: 16,
      paddingVertical: 16,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: layout.radiusMd,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    actionGrid: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 10,
      marginTop: 8,
    },
    actionButton: {
      width: "47%",
      backgroundColor: colors.surface,
      borderRadius: layout.radiusMd,
      padding: 16,
      alignItems: "center",
      borderWidth: 1,
      borderColor: colors.border,
    },
    actionIcon: {
      fontSize: 24,
      marginBottom: 8,
    },
    actionLabel: {
      color: colors.text,
      fontSize: 14,
      fontWeight: "600",
      textAlign: "center",
    },
    primaryButton: {
      backgroundColor: colors.primary,
      borderRadius: brand.buttonRadius,
      minHeight: 56,
      paddingVertical: 14,
      alignItems: "center",
      marginTop: 8,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 3,
    },
    primaryButtonText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "700",
    },
    secondaryButton: {
      backgroundColor: colors.secondary,
      borderRadius: layout.radiusMd,
      minHeight: 52,
      paddingVertical: 14,
      alignItems: "center",
      marginTop: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    secondaryButtonText: {
      color: colors.primary,
      fontSize: 16,
      fontWeight: "700",
    },
    input: {
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: layout.radiusMd,
      paddingHorizontal: 16,
      minHeight: 48,
      fontSize: 16,
      color: colors.text,
      marginBottom: 12,
    },
    label: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.text,
      marginBottom: 6,
    },
    listItem: {
      backgroundColor: colors.surface,
      borderRadius: layout.radiusMd,
      padding: 14,
      marginBottom: 8,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderColor: colors.border,
    },
    listItemTitle: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
    },
    listItemSubtitle: {
      fontSize: 13,
      color: colors.textMuted,
      marginTop: 2,
    },
    languageRow: {
      flexDirection: "row",
      justifyContent: "flex-end",
      gap: 4,
    },
    langChip: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: "rgba(255,255,255,0.12)",
      borderWidth: 1,
      borderColor: "rgba(255,255,255,0.18)",
    },
    langChipLight: {
      backgroundColor: colors.background,
      borderColor: colors.border,
    },
    langChipActive: {
      backgroundColor: "#FFFFFF",
      borderColor: "#FFFFFF",
    },
    langChipActiveLight: {
      backgroundColor: colors.secondary,
      borderColor: colors.accent,
    },
    langChipText: {
      color: "rgba(255,255,255,0.85)",
      fontSize: 11,
      fontWeight: "600",
    },
    langChipTextLight: {
      color: colors.textMuted,
    },
    langChipTextActive: {
      color: colors.primary,
    },
    errorText: {
      color: colors.danger,
      marginBottom: 8,
      fontSize: 14,
    },
    currencyBadge: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: colors.surfacePurple,
      borderRadius: 999,
      paddingHorizontal: 10,
      paddingVertical: 5,
      gap: 6,
      alignSelf: "flex-start",
      borderWidth: 1,
      borderColor: colors.border,
    },
    flagText: {
      fontSize: 16,
    },
    currencyCode: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.primary,
    },
    tabContent: {
      flex: 1,
      paddingHorizontal: 16,
      paddingVertical: 16,
      maxWidth: layout.maxContentWidth,
      alignSelf: "center",
      width: "100%",
    },
    tabCard: {
      backgroundColor: colors.surface,
      borderRadius: layout.radiusMd,
      padding: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    tabPill: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
      backgroundColor: colors.secondary,
      alignSelf: "flex-start",
    },
    tabPillText: {
      color: colors.primary,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.2,
    },
    sectionToggleRow: {
      flexDirection: "row",
      gap: 8,
      marginBottom: 16,
    },
    sectionToggle: {
      flex: 1,
      borderRadius: layout.radiusMd,
      paddingVertical: 11,
      alignItems: "center",
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sectionToggleActive: {
      backgroundColor: colors.secondary,
      borderColor: colors.accent,
    },
    sectionToggleText: {
      color: colors.textMuted,
      fontWeight: "600",
      fontSize: 14,
    },
    sectionToggleTextActive: {
      color: colors.primary,
    },
    successHeader: {
      alignItems: "center",
      marginBottom: 20,
      paddingTop: 8,
    },
    successIconWrap: {
      width: 56,
      height: 56,
      borderRadius: 14,
      backgroundColor: colors.surfaceBlue,
      alignItems: "center",
      justifyContent: "center",
      marginBottom: 14,
    },
    successTitle: {
      fontSize: 22,
      fontWeight: "700",
      color: colors.text,
      letterSpacing: -0.3,
    },
    successSubtitle: {
      fontSize: 15,
      color: colors.textMuted,
      marginTop: 6,
      textAlign: "center",
    },
    receiptCard: {
      backgroundColor: colors.surface,
      borderRadius: layout.radiusMd,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 16,
      marginBottom: 20,
    },
    receiptHeading: {
      fontSize: 12,
      fontWeight: "700",
      color: colors.textMuted,
      textTransform: "uppercase",
      letterSpacing: 0.8,
      marginBottom: 12,
    },
    receiptRow: {
      paddingVertical: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    receiptLabel: {
      fontSize: 12,
      fontWeight: "600",
      color: colors.textMuted,
      marginBottom: 4,
      textTransform: "uppercase",
      letterSpacing: 0.4,
    },
    receiptValue: {
      fontSize: 15,
      fontWeight: "600",
      color: colors.text,
      lineHeight: 21,
    },
  });
}
